### ISSUE TITLE
»Open Timeline« shows blank grey screen

### ISSUE THREAD

**Issue by mourique** [jasonjmcghee/rem#3] opened 2023-12-28 10:35 UTC
Hi! I wanted to try out the app and clicked »Start Remembering«, use my Computer for like 10 Minutes, clicked »Stop Remembering« and then »Open Timeline«. It open a fullscreen, blank grey window with no controls and no content. Is there any way i can send you debug information?

Also clicking on »Search« results in the screen i attached, it seems the screenshots are not correctly loaded?

I'd love to be able to help more on this!

<img width="2560" alt="Bildschirmfoto 2023-12-28 um 11 35 04" src="https://github.com/jasonjmcghee/rem/assets/247940/4ec79cb1-2208-4b2b-934b-4bdd47907622">

**Comment by jasonjmcghee** [comment] 2023-12-28 13:05
I've seen your issue- that's not good! I will look into it.

**Comment by jasonjmcghee** [comment] 2023-12-28 21:20
I believe this is working properly now… locally. I’m getting ready to create another build but I’m trying to do an official one with Apple (non-app store) so figuring out code signing. If it takes too long I’ll make another unofficial

**Comment by jasonjmcghee** [comment] 2023-12-28 23:18
I'm hoping this release works better for you - still plenty of issues: https://github.com/jasonjmcghee/rem/releases/tag/v0.1.2

**Comment by jasonjmcghee** [comment] 2023-12-29 04:24
@mourique Could you check `~/Library/Application\ Support/today.jason.rem` and see if there are any `mp4`s? I'm thinking ffmpeg might have failed to run. We're flying blind as there is no logging- at all.

**Comment by jasonjmcghee** [comment] 2023-12-29 15:37
No sqlite db either! I will investigate. Out of curiosity, do you have a folder at `/Users/jason/Library/Containers/today.jason.rem/Data/Library/Application Support/today.jason.rem` - the hardened app sandbox may be putting it there now instead (going to add to readme as well...)

**Comment by jarrenrocks** [comment] 2023-12-30 05:16
@jasonjmcghee This is also happening for me as well. I'm still able to paste previous context, so it seems like it's still capturing. I have .mp4 files in ~/Library/Application\ Support/today.jason.rem

M2 air, macOS Sonoma 14.0 - did a full restart as well

installed via v0.1.5dmg

**Comment by jasonjmcghee** [comment] 2023-12-30 12:23
mind trying https://github.com/jasonjmcghee/rem/releases/tag/v0.1.6?

**Comment by lotas** [comment] 2023-12-30 16:17
I have similar issue, and the reason for me why that page is blank is because it seems like no images have been taken. All `output-dd.mp4` files are zero bytes. 
Search works but i believe it only works on a window/tab titles/urls so far, so content is not visible. 
Running Sonoma 14.2.1. 
Permissions to record screen were granted and I even restarted few times.

`console` app show this kind of errors from `imagenet` process, might be relevant ?

```
Error communicating with persistent store service proxy: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.contactsd.persistence was invalidated: failed at lookup with error 159 - Sandbox restriction." UserInfo={NSDebugDescription=The connection to service named com.apple.contactsd.persistence was invalidated: failed at lookup with error 159 - Sandbox restriction.}
```

Also, seems like `0.1.6` is more resource-intensive, up to making whole system sluggish. `0.1.5` was running smoother but also not recording images :) 

Thanks! Great efforts 👏

**Comment by jasonjmcghee** [comment] 2023-12-30 16:22
Oh no! Worse? I will add a note to the release...

**Comment by jasonjmcghee** [comment] 2023-12-30 16:43
`contactsd` issue... I was really trying to follow all Apple security best practices, but concerned it's not letting it write to its own folder.

This seems relevant: https://discussions.apple.com/thread/254659981?sortBy=best

**Comment by jasonjmcghee** [comment] 2023-12-30 17:08
@lotas were you streaming with the console app when you ran `0.1.6`? Because that will absolutely cause performance issues

**Comment by jasonjmcghee** [comment] 2023-12-30 17:17
Just had a thought - in order to get things signed properly I created `ffmpegX`. I'm wondering if somehow, when the app isn't running on _my computer_ (ugh) that `ffmpegX` doesn't have access to `rem`'s `Application Support` location, due to sandboxing.

Crazy that it could _create_ the files, just not, write to them?

**Comment by jasonjmcghee** [comment] 2023-12-30 17:28
If someone runs into this, and is willing to try `xattr -c rem.app` that will remove gatekeeper stuff which should remove "sandbox". If it does, that will be pretty strong evidence of where we need to investigate / debug"

**Comment by lotas** [comment] 2023-12-30 18:05
So I did apply `xattr -c`, I have `ffmpeg` also installed on the system, and I see sqlite db growing and empty videos at `/Users/yaraslaukurmyza/Library/Containers/today.jason.rem/Data/Library/Application Support/today.jason.rem`

> It's "sluggish" feeling- is that during scrubbing in the timeline
Everything.. but I think after few restarts it got better, although Activity shows %cpu floats around 15-20% but Energy Impact shows crazy values around `380-490` (whatever units those are)
(I tried both with and without `console` running)

> Crazy that it could create the files, just not, write to them?
Is there a way to debug this?

**Comment by jasonjmcghee** [comment] 2023-12-30 19:21
Yeah that medianalysisd is ocr...

Things I'd try:
- trying to execute the ffmpeg command manually with the embedded ffmpeg
-  swapping out the embedded ffmpeg with your homebrew one
- Try building it yourself with my script!

**Comment by lotas** [comment] 2023-12-30 22:45
No luck so far, but I'm pretty sure the problem is somewhere around ffmpeg for me. Tried replacing with homebrew version but nothing's happening.

Although, when I tried to mimic the png stuff i got some codec errors like below, where my ffmpeg would run fine, but embedded one would. (maybe doing something wrong here also)
<img width="1707" alt="image" src="https://github.com/jasonjmcghee/rem/assets/83861/03a9305b-8393-4877-90e3-deed9a9bd928">

Btw, between 0.1.5 and 0.1.6 UI was "broken":
- when toggling timeline just gray window appears, in 0.1.5 it had a message in the center "nothing to remember.."
- search also stopped showing images initially, just all blank space and input is not focused, window not active.

I'm not sure how helpful that is though :)

**Comment by jasonjmcghee** [comment] 2023-12-31 00:29
The errors here seems like it wants MP4 extension. Did you try specifying the codec as h264_videotoolbox?

**Comment by jasonjmcghee** [comment] 2023-12-31 03:24
Managed to repro this, but mp4 etc. all working fine, search working etc. but getting gray timeline, until quitting and reopening. i think this is a potentially unrelated issue?

**Comment by jasonjmcghee** [comment] 2023-12-31 08:47
> when toggling timeline just gray window appears, in 0.1.5 it had a message in the center "nothing to remember.."

Made a ton of progress on this. still working on it, but things are making a lot more sense. there were some bound variables that were updating and causing repeated re-renders

**Comment by jasonjmcghee** [comment] 2023-12-31 15:41
> Managed to repro this, but mp4 etc. all working fine, search working etc. but getting gray timeline, until quitting and reopening. i think this is a potentially unrelated issue?

> when toggling timeline just gray window appears, in 0.1.5 it had a message in the center "nothing to remember.."

Both should be fixed in `0.1.8`

---------------------------

The inability for some users to write data at all is still the main issue here and _not fixed_ AFAIK.

**Comment by jasonjmcghee** [comment] 2023-12-31 15:43
@lotas

> Is there a way to debug this?

Absolutely there is, if you spin up xcode and step through the code, you should get a better sense of why it's failing

**Comment by lotas** [comment] 2023-12-31 16:51
> Absolutely there is, if you spin up xcode and step through the code, you should get a better sense of why it's failing

Sure! I will do it next year ;)

**Comment by jasonjmcghee** [comment] 2024-01-01 09:17
> complains about sqlite library missing

Did you make sure it was marked as `macos` instead of `iOS`? (as per screenshot in readme)

I'd also make sure to do `clean build` too. I have to do it pretty regularly.

**Comment by lotas** [comment] 2024-01-01 11:04
Ha! So I managed to make it work finally, it had to do with the fact that I don't have a developer account.. so I had to disable all that signing and tell "Disable Library Validation Entitlement" for sqlite .. anyways.. so it runs just fine and in that debug builds ffmpeg works flawlessly 😂  
Not sure what's not right with the release package.

**Comment by jasonjmcghee** [comment] 2024-01-01 15:22
@lotas thank you- yeah that tells me there’s still something to do with either hardened runtime / app sandbox that’s preventing it from working for people who are downloading the release.

Will continue investigating…

**Comment by jasonjmcghee** [comment] 2024-01-01 16:26
Alright. I did a bunch of... stuff... to do with entitlements etc.

Would love if someone having this issue try https://github.com/jasonjmcghee/rem/releases/tag/v0.1.9

Sorry for all the failures 🤦 - I'm trying. Never released an app through apple before and all the security / codesigning stuff is throwing me for a loop.

cc @mourique @lotas

**Comment by jasonjmcghee** [comment] 2024-01-01 16:35
Also happy to invite one of you to the TestFlight, and see if _that_ works:

<img width="422" alt="image" src="https://github.com/jasonjmcghee/rem/assets/1522149/e2e52b56-4b7c-4b90-8cf5-4a6afdc70790">

**Comment by jasonjmcghee** [comment] 2024-01-01 17:23
@mourique I need to invite you via email. I can send to the one posted on your personal site? If not, feel free to email me whichever preferred email to `rem@jason.today`

**Comment by jasonjmcghee** [comment] 2024-01-01 17:31
Oof, I have to wait for external testflight app review. I'll add the latest dmg to 0.1.9 - it _should_ have the same fixes? 🤞

**Comment by lotas** [comment] 2024-01-01 17:45
I think 0.1.9 is finally recording videos and have screenshots! 🎉 Great job, thanks!

**Comment by jasonjmcghee** [comment] 2024-01-01 18:04
If @mourique signs off on 0.1.9 dmg, I’ll close!

**Comment by jasonjmcghee** [comment] 2024-01-01 20:45
it never ends! 😂 Thank YOU for reporting and helping debug! It was huge.

**Closed by jasonjmcghee** 2024-01-01 20:45 UTC
Labels: help wanted, working on it!
